### PR TITLE
[display] major update

### PR DESCRIPTION
**Pull request by bezout**
de rien

### CODE REVIEW

**Comment by charlybigoud** [comment]
Carriage return `\r` is not a good solution (at least not good enough) to write something on the previous line. Soon, I will display more variables with **non constant width** (_e.g._ iteration number) so I need to blank the whole line before writing otherwise there will be some unwanted characters.

**Comment by bezout** [comment]
Who cares going to the previous line ? Just go at the beginning of the line and re-write it.
By the way, why don't you use Qt ?

**Comment by charlybigoud** [comment]
Yep you're right,  anyway the line should be blanked. I take comment, I'll soon push a fix.
About Qt: I aimed to create a code uniquely depending on the STL... I won't use Qt to display a line :smile:

**Comment by bezout** [comment]
Qt only depends on the STL too.

**Comment by bezout** [comment]
arrête

2017-05-26 17:52 GMT+02:00 charlybigoud <notifications@github.com>:

**Pull request merged**
